POST http://localhost:3000/reports
content-type: application/json

{
  "make": "toyota",
  "model": "coraolla",
  "year": 1980,
  "mileage": 10000,
  "lng": 0,
  "lat": 0,
  "price": 5000
}

### Approve an existing report

PATCH http://localhost:3000/reports/2
content-type: application/json

{
  "approved" : true
}

###Get an estimate for an existring vehicle
GET http://localhost:3000/reports?make=toyota&model=colla&lng=0&lat=0&mileage=2000&year=1980