
###Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email" : "tdrdg@gmx.com",
  "password" : "7tgvbnko987ztg"
}

###Create sign in existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email" : "tdrdg@gmx.com",
  "password" : "7tgvbnko987ztg"
}

###Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

###Find a user by id
GET http://localhost:3000/auth/3

###Find all users by email
GET http://localhost:3000/auth/?email=fdgd@fff.com

### Delete a user
DELETE http://localhost:3000/auth/1233

### Update a user

PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email" : "aaaa@bbbb.com"
}